### ISSUE TITLE
Bug with new lua 5.4.7 version on Macos

### ISSUE THREAD

**Issue by noahlias** [FelixKratz/SbarLua#29] opened 2024-06-29 15:15 UTC
When I use lua 5.4.7 and with your lua config , the battery info seems to be wrong.
<img width="350" alt="image" src="https://github.com/FelixKratz/SbarLua/assets/3949397/e85352a0-9968-4ce8-a813-15363f777591">

So I recompile the lua with 5.4.4 
<img width="586" alt="image" src="https://github.com/FelixKratz/SbarLua/assets/3949397/d0ee6d50-6681-411e-ab47-1968c9c80108">

and it works.
<img width="213" alt="image" src="https://github.com/FelixKratz/SbarLua/assets/3949397/10774961-c059-4b3b-a104-4bc55855358f">

Maybe we can export it to luarocks  rock spec with spec version of lua

**Comment by waytoabv** [comment] 2024-06-30 17:33
thank you, I've had the problem since a reboot yesterday and have been going crazy trying to find the cause

**Comment by ZedMuir** [comment] 2024-07-01 23:26
Legend. Thanks for the tip.  Sourced lua-5.4.4 in the rc file and all working as expected. Would not have thought of doing this so thanks for saving me hours of headache.

**Comment by dagrlx** [comment] 2024-07-02 02:35
Another solution without having to compile is to install pkgx.sh, then install 5.4.4 with pkgx install lua@5.4.4, then modify the sketchybar script:

#!/Users/xxxxx/.pkgx/lua.org/v5.4.4/bin/lua

-- Load the sketchybar-package and prepare the helper binaries
require("helpers")
require("init")

This way you keep lua 5.4.7 and 5.4.4 without conflict.

https://pkgx.sh

**Comment by noshitsherlock** [comment] 2024-07-02 20:49
> When I use lua 5.4.7 and with your lua config , the battery info seems to be wrong. <img alt="image" width="350" src="https://private-user-images.githubusercontent.com/3949397/344403959-e85352a0-9968-4ce8-a813-15363f777591.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NTIyNDEsIm5iZiI6MTcxOTk1MTk0MSwicGF0aCI6Ii8zOTQ5Mzk3LzM0NDQwMzk1OS1lODUzNTJhMC05OTY4LTRjZTgtYTgxMy0xNTM2M2Y3Nzc1OTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMjAyNTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmI2YWM2MDg3ZTNkZDg3ODUzNzkxODE1N2Q0YTk2YjAxNWQ3NTdjNWUwYzIzNWFlNWE0YjliMWY5NDVhYzBhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sBzlzqGSUQhKHa6n-w2ki2MRytourmDVS5q8Q7x4DGE">
> 
> So I recompile the lua with 5.4.4 <img alt="image" width="586" src="https://private-user-images.githubusercontent.com/3949397/344404166-d0ee6d50-6681-411e-ab47-1968c9c80108.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NTIyNDEsIm5iZiI6MTcxOTk1MTk0MSwicGF0aCI6Ii8zOTQ5Mzk3LzM0NDQwNDE2Ni1kMGVlNmQ1MC02NjgxLTQxMWUtYWI0Ny0xOTY4YzljODAxMDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMjAyNTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjI3YmRhZWM0YjZmMDBlMmU5YzJkZDEzMDA2ODBiNWI4MWYyNGZiZTJmOTIwYjBiNDg5MzUxMWJiYjIxYmRhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TvF6cbLeyhOcrAMUeWGo98pz_MOo3wqEhKU_ipmhpmk">
> 
> and it works. <img alt="image" width="213" src="https://private-user-images.githubusercontent.com/3949397/344404117-10774961-c059-4b3b-a104-4bc55855358f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NTIyNDEsIm5iZiI6MTcxOTk1MTk0MSwicGF0aCI6Ii8zOTQ5Mzk3LzM0NDQwNDExNy0xMDc3NDk2MS1jMDU5LTRiM2ItYTEwNC00YmM1NTg1NTM1OGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMjAyNTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzY2NDkyZWZkZTg3OTQyNWQ3OTJhYTFiODc5YmUxYmUxYzIwMTY3NzAyMTQ5ZGRmMmZmM2JkZDFiYmMxNTY0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KoXRJM-_GQkWerQDCndf3frogGwXdXJKD4j7w_qS9V4">
> 
> Maybe we can export it to luarocks rock spec with spec version of lua

Sorry but how do write that path? Can't seem to get it right 😂

**Comment by DensityInfinite** [comment] 2024-07-03 23:20
> Another solution without having to compile is to install pkgx.sh, then install 5.4.4 with pkgx install lua@5.4.4, then modify the sketchybar script:
> 
> #!/Users/xxxxx/.pkgx/lua.org/v5.4.4/bin/lua
> 
> -- Load the sketchybar-package and prepare the helper binaries require("helpers") require("init")
> 
> This way you keep lua 5.4.7 and 5.4.4 without conflict.
> 
> https://pkgx.sh

Absolute legend. Thank you so much. I've been pulling my hair out over this since yesterday. Followed this and it's working as expected.

**Comment by pkdevel** [comment] 2024-07-04 06:28
i dropped most of the lua widgets in favour of sketchybar aliases
it surely is not the same, as they are purely a visual representation of the menu bar icon, hence not clickable

`¯\_(ツ)_/¯`

have a look:
![image](https://github.com/FelixKratz/SbarLua/assets/2041818/d5e60ae6-cc35-4a17-be10-f4771bb9c2d6)

i like that approach, since i'm not using menu bar items very often.
i found myself using the menu bar most of the time anyway (control centre)

**Comment by noshitsherlock** [comment] 2024-07-04 07:09
> Another solution without having to compile is to install pkgx.sh, then install 5.4.4 with pkgx install lua@5.4.4, then modify the sketchybar script:
> 
> #!/Users/xxxxx/.pkgx/lua.org/v5.4.4/bin/lua
> 
> -- Load the sketchybar-package and prepare the helper binaries require("helpers") require("init")
> 
> This way you keep lua 5.4.7 and 5.4.4 without conflict.
> 
> https://pkgx.sh

I tried this as well, but when installing I get this message. Any idea @dagrlx ?

![image](https://github.com/FelixKratz/SbarLua/assets/3532879/5cf55556-2766-45fb-88b8-294ecdf48ea0)

**Comment by noshitsherlock** [comment] 2024-07-04 12:31
Don't know why, but running this solved the problem and the directory .pkgx was created and after that I could use your fix and it worked :D 

`pkgx lua@5.4.4 --version`

**Comment by dagrlx** [comment] 2024-07-04 14:43
> > Another solution without having to compile is to install pkgx.sh, then install 5.4.4 with pkgx install lua@5.4.4, then modify the sketchybar script:
> > #!/Users/xxxxx/.pkgx/lua.org/v5.4.4/bin/lua
> > -- Load the sketchybar-package and prepare the helper binaries require("helpers") require("init")
> > This way you keep lua 5.4.7 and 5.4.4 without conflict.
> > https://pkgx.sh
> 
> I tried this as well, but when installing I get this message (so nothing exists in that path for me). Any idea @dagrlx ?
> 
> ![image](https://private-user-images.githubusercontent.com/3532879/345731214-5cf55556-2766-45fb-88b8-294ecdf48ea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDI3ODQsIm5iZiI6MTcyMDEwMjQ4NCwicGF0aCI6Ii8zNTMyODc5LzM0NTczMTIxNC01Y2Y1NTU1Ni0yNzY2LTQ1ZmItODhiOC0yOTRlY2RmNDhlYTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMTQxNDQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2EzZWNmNzI4YTgzOGNmYjkyMmM1ZjI2ZmU4YmMxODMwMDFlZGI1MDg2OTA4MmU4YTc3ODgxZTY1MDYwODA1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bqptC5XHDjRn6l34wuy0nKG6oCDeNCGeQtRwDFIESFI)

Hello,
What you are being told here is that the .local/bin directory is not in your shell's environment variables.

Actually it was my mistake, I mixed 2 different things, it was not necessary to run pkgx install lua@5.4.4, unless you want to have it available in your shell environment.

Just run pkgx lua@5.4.4 -version in the terminal, then apply the change to the sketchybar script.

Two things you should know about pkgx:

1.- If you run pkgx install install lua@5.4.4, pkgx will install the app in .local/bin and so it will be available throughout your environment, as long as you have .local./bin in your path variable. 
 
If you run pkgx lua@5.4.4 -version, what pkgx does is to download the package and create the cache in .pkgx, so it is not available for your environment, what you actually do is to run the app without having it integrated to your system (this is the option I used in the sketchybar script config).

**Comment by FelixKratz** [comment] 2024-07-06 12:57
Should be fixed on master https://github.com/FelixKratz/SbarLua/commit/ea95c2b5562d59a285b39d99075fc7571fe7b31a

**Closed by FelixKratz** 2024-07-06 12:57 UTC
