### ISSUE TITLE
Defunct processes

### ISSUE THREAD

**Issue by khaneliman** [FelixKratz/SbarLua#12] opened 2024-02-25 03:27 UTC
Been working on migrating config to use sbar lua and see huge performance issues while going through development. Had numerous times i've had to force restart computer because it locks up while restarting sketchybar over and over from config changes. I recently woke my computer up and computer was unresponsive and had to force restart. I saw a bunch of defunct processes in btop and was curious if it might be an issue with how the api is managing all the child processes from the various subscriptions or if it's just my lack of understanding of lua in my migration of my existing config https://github.com/khaneliman/khanelinix/pull/81. I was using latest release version, going to try building from master branch. 

<img width="813" alt="image" src="https://github.com/FelixKratz/SbarLua/assets/1778670/9208d9f5-a0a0-46db-a64b-d95853923a4f">

**Comment by FelixKratz** [comment] 2024-02-25 07:36
Thats odd, in theory, the lua process should be killed as well in a restart. Could be that there is some edge case where this doesnt work. Note that there is only ever one process/thread doing the event handling, such that os.execute or io.popen will block all event handling. This is why the lua callbacks should not take too long to execute. For long lasting calls (as brew update/brew upgrade etc) regular async scripts should be used (as before via the script property or by using sbar.exec). See also #5 for more discussion about this.

I will see if I can repro this issue.

**Comment by khaneliman** [comment] 2024-02-25 15:40
Hmm.. alright. So issue could be caused from converting all my scripts to lua event handle subscriptions. I assumed it would be a faster communication, but if they are all single threaded blocking that would be much slower than just invoking my bash scripts. Does sbar.exec just run bash scripts or commands directly to sketchybar? Or does it support running lua scripts as well so i can keep all my config in one language?

**Comment by FelixKratz** [comment] 2024-02-25 16:14
Yeah, well, the communication is *much* faster. Problem is that we have a global state, which we need to protect in lua. I.e. it is possible to access and set global variables in the lua callback functions such that it is not possible to do any callback handling async in lua. We can however do fork->exec from C, which is exactly what sbar.exec does. So this is truely async and will not block the main thread.

I had an idea however, which would be nice I think. The problem seems to be that calling some program through shell is often too slow, so what could be done is to add a lua completion handler to those shell scripts.

Essentially something like this:
```lua
sbar.exec("brew outdated", function(result)
  print(result)
end)
```

Now what we do in C behind the courtains is the following:
* We spawn a new thread
* The new thread executes the command completely async
* once the command has returned, we post an event into the main thread CFRunLoop containing the result
* The runloop eventually calls the completion handler with the result as an argument, which can then be handled in lua.

The problem is that *only* the result variable will be reliably accessible in the completion handler because it is essentially arbitrary at which point the RunLoop calls the function. So none of the other variables from the scope of sbar.exec will be available.
 
This adds quite some complexity but I think it really is the best way to keep the event callback thread from being blocked by os.execute or io.popen

**Comment by khaneliman** [comment] 2024-02-25 17:21
> This adds quite some complexity but I think it really is the best way to keep the event callback thread from being blocked by os.execute or io.popen

Yeah, I do like this idea of a callback to support these types of commands. I assume you were saying you still need to implement the callback or is that possible currently? I tried implementing this and I see the console output of the commands being run but not seeing the function getting hit.

**Comment by FelixKratz** [comment] 2024-02-25 17:25
No its not implemented yet, this was just an idea.

**Comment by FelixKratz** [comment] 2024-02-25 19:15
I quickly hacked this together and it seems to work just as intended: https://github.com/FelixKratz/SbarLua/commit/19a66adb76ef08ec4d2ce906cbf752d1e0560b81

**Comment by khaneliman** [comment] 2024-02-25 19:31
Sweet, I'll try updating code to use that and see if it works for me. Appreciate the quick help!

**Comment by khaneliman** [comment] 2024-02-25 21:57
Seems to be a lot more responsive with the bar. But, I still see a handful of defunct processes while using Sbarlua. My windowmanager process kept locking up my computer still and I think that issue might be related to the hotload. I disabled hotloading and the windowmanager process appears to not runaway with usage. *knocks on wood* Before, with hotload enabled, I had to kill windowmanager and manually restart sketchybar otherwise i'd see in my logs that it appeared to be reinitializing nonstop and windowmanager cpu usage and memory kept ballooning.

**Comment by shajra** [comment] 2024-02-26 02:39
I like the direction that `sbar.exec` has gone.  Can we make this API support exit codes?  Or maybe I need to handle exit codes as part of the command?  I can do that... wrap it in an if-then-else to always get parseable output.  Maybe a little circuitous, because all the information I need is already in the exit code.

**Comment by shajra** [comment] 2024-02-26 03:38
Okay, so I went from a configuration that wasn't really using `sbar.exec` at all (only once to spawn the CPU "helper" app) to a configuration that was using `sbar.exec` everywhere I was using an `os.exec` or a `popen`.

The performance improvement was noticeable (really optimistic for this work to get hardened).  But I also saw the same flood of "defunct" zombie processes reported in this issue.  Seems to point to a bug in the `sbar.exec` implementation.  Maybe something like ignoring SIGCHLD signal of the child process.  I'll report back if I play with code more and find something concrete.  Have to switch other stuff for now, though.

**Comment by FelixKratz** [comment] 2024-02-26 06:40
I think the problem should be fixed by this: https://github.com/FelixKratz/SbarLua/commit/64a6e0d0017cd0bff4926ad4ded6d0c0b458e69d
Thanks @shajra for reminding me that I forgot to handle SIGCHLD. I now handle it the same way as in sketchybar.

**Comment by shajra** [comment] 2024-02-26 07:15
Okay, I validated that your (much cleaner) approach works.  And thanks for the note about the alarm.  Setting `alarm(0)` in my CPU daemon seems to work well to avoid it getting killed.

Everything works swimmingly now, as far as I can tell.  The CPU can still climb from all the silly processing with process invocations, but at least it's all done asynchronously.  I am curious to see how much of that CPU climb can be reduced with Lua everywhere once your other Lua projects are ready.  But for now, this is more than fine.

**Comment by FelixKratz** [comment] 2024-02-26 07:26
Maybe the exit code of the command could be supplied as the second argument to the completion handler. That should be fairly simple to do. Then one can choose to ignore it by simply not making the second argument available in the completion handler.

**Comment by khaneliman** [comment] 2024-02-26 13:40
> I think the problem should be fixed by this: [64a6e0d](https://github.com/FelixKratz/SbarLua/commit/64a6e0d0017cd0bff4926ad4ded6d0c0b458e69d) Thanks @shajra for reminding me that I forgot to handle SIGCHLD. I now handle it the same way as in sketchybar.

Looks like process list is clear of all the defunct processes for me, now. Appreciate the quick fixes for this stuff!

**Comment by FelixKratz** [comment] 2024-02-26 15:27
Nice! Do you still see the infinite hotload loop? I think this might a problem when the config changes something in the directory of the config itself... Then the bar will enter a hotload loop. I think I will prohibit this on the sketchybar hotload handling side by introducing some kind of timeout, where a config can not reload arbitrarily often in a certain time period.

**Closed by FelixKratz** 2024-02-26 15:27 UTC

**Comment by FelixKratz** [comment] 2024-02-26 17:18
Had to swap out the default `os.execute` implementation because it calls `system(1)` and gets stuck while trying to retrieve the child exit code because we immediately reap it by ignoring SIGCHLD.

**Comment by khaneliman** [comment] 2024-02-27 02:43
> Nice! Do you still see the infinite hotload loop? I think this might a problem when the config changes something in the directory of the config itself... Then the bar will enter a hotload loop. I think I will prohibit this on the sketchybar hotload handling side by introducing some kind of timeout, where a config can not reload arbitrarily often in a certain time period.
> 
> EDIT: Implemented on sketchybar master.

I re-enabled hotload after your latest commit, seems to have fixed the loop for me. Thanks
